# Project information
site_name: XYZ Maps - Open Documentation
site_description: Free Open Source Mapping Platform
site_author: XYZ Maps and contributors
site_url: https://xyzmaps.github.io/xyz-documentation
site_dir: ../site

# Repository
repo_name: xyzmaps/xyz-documentation
repo_url: https://github.com/xyzmaps/xyz-documentation
#edit_uri:

# Copyright
copyright: "Copyright &copy; 2022-2023 XYZ Maps and contributors"

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: white
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png

# Page tree
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - XYZ Maps API:
      - Overview: api/index.md
      - Quick Start:
          - Read Spaces: api/quickstart/readspaces.md
          - Create a Space: api/quickstart/createspace.md
          - Write to a Space: api/quickstart/writetospace.md
          - Use Activity Log: api/quickstart/activitylog.md
      - Concepts:
          - GeoJSON Basics: api/concepts/geojsonbasics.md
          - Namespaces: api/concepts/namespaces.md
          - Tags and Tagging: api/concepts/tags.md
          - Tiles: api/concepts/tiles.md
          - JSON Schema: api/concepts/jsonschema.md
      - Walkthrough:
          - Create a Space: api/walkthrough/creatingaspace.md
          - Add and Delete Features: api/walkthrough/addinganddeleting.md
          - Search by Bounding Box: api/walkthrough/searchbyboundingbox.md
          - Search by Tags: api/walkthrough/searchbytags.md
          - Iterate over Features: api/walkthrough/iterateoverfeatures.md
          - Use Schema Validation: api/walkthrough/schemavalidation.md
      - Developer Guide:
          - Work with Spaces: api/devguide/workwithspaces.md
          - Work with Features: api/devguide/workwithfeatures.md
          - Tags: api/devguide/tagging.md
          - Access Features: api/devguide/accessingfeatures.md
          - Search for Features: api/devguide/propertiessearch.md
          - Spatial Search for Features: api/devguide/spatialsearch.md
          - Adjust searchable properties: api/devguide/searchableproperties.md
          - Visualization and Clustering:
              - viz: api/devguide/visualization.md
              - hexbin (H3): api/devguide/hexbin.md
              - quadbin: api/devguide/quadbin.md
          - Work with Activity Log: api/devguide/activitylogguide.md
          - Common Errors: api/devguide/commonerrors.md
      - Advanced concepts: cli/datahub_add-on.md
      - API Reference: api/apireference.md
  - XYZ Maps UI:
      - Overview: ui/index.md
      - Get started: ui/gettingstarted.md
      - Display your space: ui/yourxyzspace.md
      - Style your data: ui/styleyourdata.md
      - Add interactivity: ui/tapfeature.md
  - XYZ Maps Tools:
      - XYZ Maps CLI:
          - Overview: cli/index.md
          - Basic features: cli/basic-features.md
          - Add-on features: cli/add-on.md
          - Tutorials:
              - Shapefiles: cli/tutorials/shapefiles.md
              - Hexbins: cli/tutorials/cli_hexbins.md
              - Group by in CSV: cli/tutorials/group_by.md
          - Command reference: cli/command-reference.md
      - XYZ Space Invader: cli/space-invader/index.md
      - XYZ Spaces for Python: cli/tools#xyz-spaces-for-python
      - GeoJSON Viewer:
          - Overview: cli/viewer-tool/index.md
          - GeoJSON Basics: api/concepts/geojsonbasics.md
          - Advanced Features: cli/viewer-tool/advanced.md
  - Useful Links: api/links.md
      # - Open Datasets:
      #     - Buildings: cli/topics/microsoft-buildings.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
